fix(infra): fix ci-cd

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -39,7 +39,8 @@ jobs:
       - name: Wait for DynamoDB Local Initialization
         run: |
           echo "Waiting for DynamoDB Initializer to complete setup..."
-          timeout 180 bash -c 'until docker inspect dynamodb-initializer | grep -q "Exited (0)"; do echo -n "."; sleep 10; done' || { echo "DynamoDB Initializer did not complete successfully. Aborting."; exit 1; }
+          # Aumenta o timeout para 300 segundos (5 minutos) para dar mais tempo para o DynamoDB e suas tabelas
+          timeout 300 bash -c 'until docker inspect dynamodb-initializer | grep -q "Exited (0)"; do echo -n "."; sleep 10; done' || { echo "DynamoDB Initializer did not complete successfully. Aborting."; exit 1; }
           echo "DynamoDB Local and table setup completed by Initializer!"
 
       - name: Wait for Wiremock to be healthy
@@ -48,8 +49,19 @@ jobs:
           timeout 120 bash -c 'until [ "$(docker inspect -f {{.State.Health.Status}} wiremock)" = "healthy" ]; do echo -n "."; sleep 5; done' || { echo "Wiremock did not become healthy. Aborting."; exit 1; }
           echo "Wiremock is healthy!"
 
-      - name: Build and Test with Maven
+      - name: Wait for Kafka and Schema Registry to be ready
+        run: |
+          echo "Waiting for Kafka and Schema Registry..."
+          # Espera o Control Center ficar saudável, que por sua vez depende de Kafka e Schema Registry
+          timeout 300 bash -c 'until [ "$(docker inspect -f {{.State.Health.Status}} control-center)" = "healthy" ]; do echo -n "."; sleep 10; done' || { echo "Kafka or Schema Registry did not become healthy. Aborting."; exit 1; }
+          echo "Kafka and Schema Registry are ready!"
+
+      - name: Build and Run Unit/Integration Tests with Maven
         run: mvn clean install -Dskip.native.build=true
+
+      - name: Run End-to-End (E2E) Tests
+        run: mvn integration-test -Pnative -Dspring-boot.build-image.dockerfile=src/main/resources/docker/Dockerfile -Dspring-boot.build-image.build-context=.
+
 
       - name: Upload JaCoCo Code Coverage Report
         uses: actions/upload-artifact@v4
@@ -77,5 +89,8 @@ jobs:
 
       - name: Build Native Image with Paketo Buildpacks
         run: |
-          mvn spring-boot:build-image -Pnative -Dspring-boot.build-image.dockerfile=src/main/resources/docker/Dockerfile -Dspring-boot.build-image.build-context=.
+          # Use o profile `native` que você já tem configurado para o build da imagem.
+          # O `-Dspring-boot.build-image.dockerfile` e `-Dspring-boot.build-image.build-context` são desnecessários aqui,
+          # pois o plugin spring-boot-maven-plugin já sabe como construir a imagem.
+          mvn spring-boot:build-image -Pnative
           echo "Native Image built successfully using Paketo Buildpacks."
