fix(infra): fix ci-cd

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -31,10 +31,10 @@ jobs:
           restore-keys: |
             ${{ runner.os }}-maven-
 
-      - name: Start Docker Compose Infrastructure (DynamoDB Local & Initializer)
+      - name: Start Docker Compose Infrastructure
         run: |
-          sudo apt-get update && sudo apt-get install -y docker-compose netcat-openbsd 
-          docker compose -f src/main/resources/docker/docker-compose.yml up -d 
+          sudo apt-get update && sudo apt-get install -y docker-compose netcat-openbsd
+          docker compose -f src/main/resources/docker/docker-compose.yml up -d
 
       - name: Wait for DynamoDB Local Initialization
         run: |
@@ -42,13 +42,11 @@ jobs:
           timeout 180 bash -c 'until docker inspect dynamodb-initializer | grep -q "Exited (0)"; do echo -n "."; sleep 10; done' || { echo "DynamoDB Initializer did not complete successfully. Aborting."; exit 1; }
           echo "DynamoDB Local and table setup completed by Initializer!"
 
-          echo "Waiting for Kafka to be healthy..."
-          timeout 180 bash -c 'until docker inspect kafka | grep -q "\"Status\": \"healthy\""; do echo -n "."; sleep 10; done' || { echo "Kafka did not become healthy. Aborting."; exit 1; }
-          echo "Kafka is healthy!"
-
-          echo "Waiting for Schema Registry to be healthy..."
-          timeout 180 bash -c 'until docker inspect schema-registry | grep -q "\"Status\": \"healthy\""; do echo -n "."; sleep 10; done' || { echo "Schema Registry did not become healthy. Aborting."; exit 1; }
-          echo "Schema Registry is healthy!"
+      - name: Wait for Wiremock to be healthy
+        run: |
+          echo "Waiting for Wiremock to be healthy..."
+          timeout 120 bash -c 'until [ "$(docker inspect -f {{.State.Health.Status}} wiremock)" = "healthy" ]; do echo -n "."; sleep 5; done' || { echo "Wiremock did not become healthy. Aborting."; exit 1; }
+          echo "Wiremock is healthy!"
 
       - name: Build and Test with Maven
         run: mvn clean install -Dskip.native.build=true
